#!/usr/bin/env bash
# Run the CoasterHunterCore tests without Xcode.
#
# `swift test` needs XCTest, which Command Line Tools does not ship. This
# compiles the same test files against Tools/XCTestShim.swift and runs them as
# an executable, so the sensor maths, ranking and entitlement logic are actually
# verified rather than merely written.
#
# Once Xcode is installed, `swift test` runs the identical files natively and
# this script becomes redundant.

set -euo pipefail
cd "$(dirname "$0")/.."

SDK=$(xcrun --show-sdk-path)
BUILD=".build/shimtests"
mkdir -p "$BUILD"

# Discover `final class X: XCTestCase` and its `func testY()` methods, then
# generate a main that calls each one. Reflection-based discovery would need the
# Objective-C runtime, which the shim deliberately avoids.
python3 - "$BUILD/main.swift" <<'PY'
import re, sys, pathlib

out = pathlib.Path(sys.argv[1])
cases = []

for path in sorted(pathlib.Path("Tests").rglob("*.swift")):
    text = path.read_text(encoding="utf-8")
    current = None
    for line in text.splitlines():
        cls = re.match(r'\s*(?:final\s+)?class\s+(\w+)\s*:\s*XCTestCase', line)
        if cls:
            current = cls.group(1)
            cases.append((current, []))
            continue
        fn = re.match(r'\s*func\s+(test\w*)\s*\(\s*\)(\s*throws)?', line)
        if fn and current:
            cases[-1][1].append((fn.group(1), bool(fn.group(2))))

lines = [
    "// Generated by Tools/run-tests.sh — do not edit.",
    "import Foundation",
    "",
    "var total = 0",
    "var failed = 0",
    "",
]
for cls, methods in cases:
    if not methods:
        continue
    lines.append(f'print("\\n\\u{{001B}}[1m{cls}\\u{{001B}}[0m")')
    for name, throwing in methods:
        call = f"try suite.{name}()" if throwing else f"suite.{name}()"
        lines += [
            "do {",
            f"  let suite = {cls}()",
            "  suite.setUp()",
            "  TestReporter.failures = []",
            f'  TestReporter.currentTest = "{cls}.{name}"',
            f"  {call}",
            "  suite.tearDown()",
            "  total += 1",
            "  if TestReporter.failures.isEmpty {",
            f'    print("  \\u{{001B}}[32m\\u{{2713}}\\u{{001B}}[0m {name}")',
            "  } else {",
            "    failed += 1",
            f'    print("  \\u{{001B}}[31m\\u{{2717}}\\u{{001B}}[0m {name}")',
            '    for f in TestReporter.failures {',
            '      print("      \\(f.file):\\(f.line)  \\(f.message)")',
            "    }",
            "  }",
            "} catch {",
            "  total += 1; failed += 1",
            f'  print("  \\u{{001B}}[31m\\u{{2717}}\\u{{001B}}[0m {name} — threw \\(error)")',
            "}",
        ]

lines += [
    "",
    'print("")',
    'print("\\(total - failed)/\\(total) tests passed, \\(TestReporter.assertions) assertions")',
    "exit(failed == 0 ? 0 : 1)",
]
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"generated {sum(len(m) for _, m in cases)} test invocations across {len(cases)} suites")
PY

# @testable needs the library built with testing enabled, so compile everything
# into one module rather than linking a separate one.
swiftc -Onone -swift-version 5 -D SHIM_TESTS \
  -sdk "$SDK" -target x86_64-apple-macos13.0 \
  -o "$BUILD/run-tests" \
  Tools/XCTestShim.swift \
  $(find Sources -name '*.swift') \
  $(find Tests -name '*.swift') \
  "$BUILD/main.swift"

"$BUILD/run-tests"
